"""
Demo data — sample posts for testing the newsletter pipeline without API access.
"""

from datetime import datetime, timezone, timedelta
from src.fetcher import Post


def get_demo_posts():
    """Generate realistic sample AI posts for demonstration."""
    now = datetime.now(timezone.utc)

    posts = [
        Post(
            id="demo_001",
            author="OpenAI",
            author_handle="@OpenAI",
            text="Introducing GPT-5 Turbo — our fastest and most capable model yet. 3x faster inference, 60% cost reduction, and native multimodal reasoning. Available today in the API. https://openai.com/gpt5-turbo",
            timestamp=now - timedelta(hours=2),
            url="https://x.com/OpenAI/status/demo001",
            likes=45200,
            retweets=12800,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_002",
            author="AndrewYNg",
            author_handle="@AndrewYNg",
            text="New research from Stanford: 'Scaling Laws for Mixture of Experts' shows that MoE architectures follow different power laws than dense transformers. Key insight: you need 4x more data to efficiently train MoE models. Paper: https://arxiv.org/abs/2024.xxxxx",
            timestamp=now - timedelta(hours=4),
            url="https://x.com/AndrewYNg/status/demo002",
            likes=8900,
            retweets=3200,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_003",
            author="karpathy",
            author_handle="@karpathy",
            text="Pro tip for fine-tuning LLMs: instead of training on all tokens equally, weight your loss function by token importance. I've seen 15-20% improvement on downstream tasks using this simple trick. Here's a quick thread on how to implement it 🧵",
            timestamp=now - timedelta(hours=3),
            url="https://x.com/karpathy/status/demo003",
            likes=15600,
            retweets=4100,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_004",
            author="huggingface",
            author_handle="@huggingface",
            text="🚀 Just released: Transformers v5.0! Major updates include native GGUF support, built-in quantization pipelines, and a completely rewritten training loop. pip install --upgrade transformers https://github.com/huggingface/transformers",
            timestamp=now - timedelta(hours=5),
            url="https://x.com/huggingface/status/demo004",
            likes=12300,
            retweets=5600,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_005",
            author="GoogleDeepMind",
            author_handle="@GoogleDeepMind",
            text="Our new Gemini 2.5 Pro achieves SOTA on 15 benchmarks including MMLU, HumanEval, and MATH. The model uses a novel 'Thinking Tokens' architecture that enables chain-of-thought reasoning within the attention mechanism itself.",
            timestamp=now - timedelta(hours=1),
            url="https://x.com/GoogleDeepMind/status/demo005",
            likes=32100,
            retweets=9800,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_006",
            author="LangChainAI",
            author_handle="@LangChainAI",
            text="LangGraph Studio v2.0 is here! Build, debug, and deploy agentic AI workflows visually. New features: real-time state inspection, breakpoints, time-travel debugging, and one-click deployment to LangServe. https://langchain.com/langgraph-studio",
            timestamp=now - timedelta(hours=6),
            url="https://x.com/LangChainAI/status/demo006",
            likes=7800,
            retweets=2900,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_007",
            author="ylecun",
            author_handle="@ylecun",
            text="Important research direction: Joint Embedding Predictive Architecture (JEPA) combined with world models is showing remarkable results in video understanding. Our latest paper demonstrates zero-shot video reasoning capabilities. https://arxiv.org/abs/2024.yyyyy",
            timestamp=now - timedelta(hours=7),
            url="https://x.com/ylecun/status/demo007",
            likes=11200,
            retweets=3800,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_008",
            author="anthropic",
            author_handle="@anthropic",
            text="Announcing Claude's new computer use capability in general availability. Claude can now safely interact with desktop applications, browse the web, and complete multi-step workflows autonomously. Enterprise-ready with audit logging and guardrails.",
            timestamp=now - timedelta(hours=3),
            url="https://x.com/anthropic/status/demo008",
            likes=28500,
            retweets=8200,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_009",
            author="hardmaru",
            author_handle="@hardmaru",
            text="Fascinating trend: AI startups are increasingly adopting 'small model + great UX' strategy instead of competing on model size. Cursor, v0, and Bolt are perfect examples. The moat is in the product, not the model.",
            timestamp=now - timedelta(hours=8),
            url="https://x.com/hardmaru/status/demo009",
            likes=6700,
            retweets=1900,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_010",
            author="GaryMarcus",
            author_handle="@GaryMarcus",
            text="New EU AI Act enforcement begins today. Key requirements for high-risk AI systems: mandatory risk assessments, human oversight provisions, and transparency obligations. Every AI company operating in Europe needs to comply. Here's what you need to know:",
            timestamp=now - timedelta(hours=5),
            url="https://x.com/GaryMarcus/status/demo010",
            likes=9400,
            retweets=4100,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_011",
            author="karpathy",
            author_handle="@karpathy",
            text="How to build a RAG system that actually works in production: 1) Chunk at semantic boundaries, not fixed tokens 2) Use hybrid search (BM25 + embeddings) 3) Re-rank with a cross-encoder 4) Always include metadata filters. Detailed guide: https://github.com/karpathy/rag-guide",
            timestamp=now - timedelta(hours=10),
            url="https://x.com/karpathy/status/demo011",
            likes=22100,
            retweets=7300,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_012",
            author="OpenAI",
            author_handle="@OpenAI",
            text="Sora is now available to all Plus and Pro subscribers. Create up to 60-second videos with consistent characters, physics, and camera movements. We've also added an editing timeline for frame-by-frame control.",
            timestamp=now - timedelta(hours=4),
            url="https://x.com/OpenAI/status/demo012",
            likes=67800,
            retweets=21000,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_013",
            author="huggingface",
            author_handle="@huggingface",
            text="Tutorial: How to serve a 70B parameter model on a single GPU using dynamic quantization + speculative decoding. We achieved 45 tokens/sec on an A100 with minimal quality loss. Full notebook and benchmarks: https://huggingface.co/blog/efficient-70b",
            timestamp=now - timedelta(hours=9),
            url="https://x.com/huggingface/status/demo013",
            likes=5600,
            retweets=2100,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_014",
            author="elonmusk",
            author_handle="@elonmusk",
            text="xAI raises $12B Series C at $50B valuation. Grok 3 training on the Memphis supercluster is progressing ahead of schedule. The model will feature real-time access to X data and multimodal capabilities at launch.",
            timestamp=now - timedelta(hours=6),
            url="https://x.com/elonmusk/status/demo014",
            likes=89000,
            retweets=15600,
            is_retweet=False,
            is_reply=False,
        ),
        Post(
            id="demo_015",
            author="LangChainAI",
            author_handle="@LangChainAI",
            text="Best practice: When building AI agents, always implement a 'plan → verify → act' loop instead of 'think → act'. The verification step catches 73% of hallucination-induced errors before they reach the user. Example implementation in our docs.",
            timestamp=now - timedelta(hours=11),
            url="https://x.com/LangChainAI/status/demo015",
            likes=4300,
            retweets=1600,
            is_retweet=False,
            is_reply=False,
        ),
    ]

    return posts
